## Practical Questions:NumPy

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

# Creating a 3x3 array with random integers between 1 and 100
array_3X3= np.random.randint(1,100, size=(3,3))
print("Original 3x3 array:")
print(array_3X3)

# Interchange rows and columns
transposed_array= array_3X3.T
print("\nTransposed 3x3 array: ")
print(transposed_array)



Original 3x3 array:
[[31 43 39]
 [71 69 72]
 [18 96 28]]

Transposed 3x3 array: 
[[31 71 18]
 [43 69 96]
 [39 72 28]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [2]:
import numpy as np

# Creating a 1D array with 10 elements
arr_1D= np.arange(10)
print("1D Array: ")
print(arr_1D)

# Reshaping into 2x5 array
Reshaped_2x5= np.reshape(arr_1D,(2,5))
print('\nReshaped into 2x5 array: ')
print(Reshaped_2x5)

# Reshaping into 5x2 array
Reshaped_5x2= arr_1D.reshape(5,2)
print('\nReshaped into 5x2: ')
print(Reshaped_5x2)

1D Array: 
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 array: 
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2: 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [3]:
# Creating a 4x4 array with random float Valules
array_4x4= np.random.rand(4,4)
print("4x4 Array:")
print(array_4x4)

# Adding a border of Zeros around it
array_6x6= np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print('\n6x6 array with a border of Zeros')
print(array_6x6)

4x4 Array:
[[0.49507478 0.92390273 0.22186741 0.95080769]
 [0.36473529 0.78727532 0.13906918 0.94654362]
 [0.16225478 0.64047642 0.92121761 0.99438099]
 [0.94168168 0.27499166 0.25799626 0.79198546]]

6x6 array with a border of Zeros
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.49507478 0.92390273 0.22186741 0.95080769 0.        ]
 [0.         0.36473529 0.78727532 0.13906918 0.94654362 0.        ]
 [0.         0.16225478 0.64047642 0.92121761 0.99438099 0.        ]
 [0.         0.94168168 0.27499166 0.25799626 0.79198546 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [4]:
array_step= np.arange(10,60,5)
print("Array form 10 to 60 with a step of 5:")
print(array_step)

Array form 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [5]:
string_array= np.array(['python', 'numpy', 'pandas'])
print("Orginal Array of Strings: ")
print(string_array)

# Apply uppercase Transformation
uppercase_array= np.char.upper(string_array)
print('\nUppercase Transforamtion: ')
print(uppercase_array)

# Apply Lowercase Transformation
lowercase_array= np.char.lower(string_array)
print('\nLowercase Transformation: ')
print(lowercase_array)

# Apply title case Transformation
titlecase_array= np.char.title(string_array)
print('\nTitle case Transformation: ')
print(titlecase_array)


Orginal Array of Strings: 
['python' 'numpy' 'pandas']

Uppercase Transforamtion: 
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Transformation: 
['python' 'numpy' 'pandas']

Title case Transformation: 
['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [6]:
# Creating an array of words
words_array= np.array(["Vivek", "Ram", "Sita", "Verma", "Krishna"])
print("Original array of words")
print(words_array)

# Insert a space between each character of every word
spaced_words_array=np.char.join(' ', words_array)
print('\nWords with spaces between characters: ')
print(spaced_words_array)

Original array of words
['Vivek' 'Ram' 'Sita' 'Verma' 'Krishna']

Words with spaces between characters: 
['V i v e k' 'R a m' 'S i t a' 'V e r m a' 'K r i s h n a']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [7]:
arr1= np.array([[1,2],[3,4]])
arr2= np.array([[5,6],[7,8]])
print("Array 1: ")
print(arr1)
print('\nArray 2:')
print(arr2)

#Element wise Addition
addition= np.add(arr1, arr2)
print('\nElement-wise Addition:')
print(addition)

# Element-wise subtration
subtraction= np.subtract(arr1,arr2)
print('\nElement-wise Subration: ')
print(subtraction)

# Element-wise Multiplication
multiplication= np.multiply(arr1, arr2)
print("\nElement-wise Multiplication: ")
print(multiplication)

# Element-wise Division
Division= np.divide(arr1,arr2)
print('\nElement-wise Division')
print(Division)

Array 1: 
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Element-wise Addition:
[[ 6  8]
 [10 12]]

Element-wise Subration: 
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication: 
[[ 5 12]
 [21 32]]

Element-wise Division
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [8]:
# Creating a 5x5 indentity matrix
identify_matrix= np.eye(5)
print("5x5 identity matix: ")
print(identify_matrix)

#Extract diagonal elements
diagonal_elements=np.diag(identify_matrix)
print('\nDiagonal elements')
print(diagonal_elements)

5x5 identity matix: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements
[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [10]:
# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, 100)
print("Random integers array:")
print(random_integers)

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]
print("\nPrime numbers in the array:")
print(prime_numbers)


Random integers array:
[325 141 191 388  55 633 411 130 902 804 411 225 175 773 515 845 778 299
 937 503 777 254 865 643 765 999 630 783 973 381 807 746 647 392 708 514
 484 104 105 479  23 365 849 727 465  10  21 102 413  68 710 673 670 274
 144  10 470  89 429 268 465 799 462 373 406  77 558 132 802 871 108 404
 595 547 450 601 475 815 908 523 811 917 163  75 403  74 270 251 254 954
 156 558  62 473 699 393  98 426 376 115]

Prime numbers in the array:
[191, 773, 937, 503, 643, 647, 479, 23, 727, 673, 89, 373, 547, 601, 523, 811, 163, 251]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [12]:
import numpy as np

# Creating an array of daily temperatures for a month (30 days)
temperatures = np.random.randint(0, 35, size=30)
print("Daily Temperatures:")
print(temperatures)

# Calculating weekly averages
weekly_averages = np.array([np.mean(temperatures[i:i+7]) for i in range(0, len(temperatures), 7)])
print("Weekly Averages:")
print(weekly_averages)


Daily Temperatures:
[26 27 33 32 31 24 32  8  3 21  8 24 17 24 14 17  8 24  4  9 25 18 12 10
  7 14 33  2 12 14]
Weekly Averages:
[29.28571429 15.         14.42857143 13.71428571 13.        ]
